// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/machine_law.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class MachineLawBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MachineLawBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MachineLawBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  Machine_law_Result_t Evaluate(
    String_t service,
    String_t law,
    Machine_law_Params_t parameters,
    String_t referenceDate,
    String_t effectiveDate,
    Machine_law_Params_t overwriteInput,
  ) {
    return _Evaluate(
      service,
      law,
      parameters,
      referenceDate,
      effectiveDate,
      overwriteInput,
    );
  }

  late final _EvaluatePtr =
      _lookup<
        ffi.NativeFunction<
          Machine_law_Result_t Function(
            String_t,
            String_t,
            Machine_law_Params_t,
            String_t,
            String_t,
            Machine_law_Params_t,
          )
        >
      >('Evaluate');
  late final _Evaluate =
      _EvaluatePtr.asFunction<
        Machine_law_Result_t Function(
          String_t,
          String_t,
          Machine_law_Params_t,
          String_t,
          String_t,
          Machine_law_Params_t,
        )
      >();

  Machine_law_Result_t EvaluateBetalingsRegelingRijk(
    String_t bsn,
    int sociaalMinimum,
    int inkomen,
    int totaleSchuld,
    int eerdereRegelingNietNagekomen,
  ) {
    return _EvaluateBetalingsRegelingRijk(
      bsn,
      sociaalMinimum,
      inkomen,
      totaleSchuld,
      eerdereRegelingNietNagekomen,
    );
  }

  late final _EvaluateBetalingsRegelingRijkPtr =
      _lookup<
        ffi.NativeFunction<
          Machine_law_Result_t Function(
            String_t,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Int,
          )
        >
      >('EvaluateBetalingsRegelingRijk');
  late final _EvaluateBetalingsRegelingRijk =
      _EvaluateBetalingsRegelingRijkPtr.asFunction<
        Machine_law_Result_t Function(String_t, int, int, int, int)
      >();

  Machine_law_Result_t EvaluateToeslagenWetBestaansMinimum(
    String_t bsn,
    int partner,
    int woningdeler,
    String_t bsnPartner,
    String_t woningdelerBsn,
    int leeftijd,
    int leeftijdPartner,
    int leeftijdWoningDeler,
  ) {
    return _EvaluateToeslagenWetBestaansMinimum(
      bsn,
      partner,
      woningdeler,
      bsnPartner,
      woningdelerBsn,
      leeftijd,
      leeftijdPartner,
      leeftijdWoningDeler,
    );
  }

  late final _EvaluateToeslagenWetBestaansMinimumPtr =
      _lookup<
        ffi.NativeFunction<
          Machine_law_Result_t Function(
            String_t,
            ffi.Int,
            ffi.Int,
            String_t,
            String_t,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('EvaluateToeslagenWetBestaansMinimum');
  late final _EvaluateToeslagenWetBestaansMinimum =
      _EvaluateToeslagenWetBestaansMinimumPtr.asFunction<
        Machine_law_Result_t Function(
          String_t,
          int,
          int,
          String_t,
          String_t,
          int,
          int,
          int,
        )
      >();

  int machineLawStandalone() {
    return _machineLawStandalone();
  }

  late final _machineLawStandalonePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('machineLawStandalone');
  late final _machineLawStandalone = _machineLawStandalonePtr
      .asFunction<int Function()>();

  void freeParams(Machine_law_Params_t params) {
    return _freeParams(params);
  }

  late final _freeParamsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(Machine_law_Params_t)>>(
        'freeParams',
      );
  late final _freeParams = _freeParamsPtr
      .asFunction<void Function(Machine_law_Params_t)>();

  void freeRuleResult(Machine_law_Result_t result) {
    return _freeRuleResult(result);
  }

  late final _freeRuleResultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(Machine_law_Result_t)>>(
        'freeRuleResult',
      );
  late final _freeRuleResult = _freeRuleResultPtr
      .asFunction<void Function(Machine_law_Result_t)>();
}

final class String_t extends ffi.Struct {
  @ffi.Uint16()
  external int length;

  external ffi.Pointer<ffi.Uint8> string;
}

final class Machine_law_Params_t extends ffi.Struct {
  external String_t params;
}

final class Machine_law_Result_t extends ffi.Struct {
  @ffi.Uint8()
  external int resultCode;

  external String_t resultMessage;
}
